FP        WORD  X'001000'
SP        WORD  X'001000'
ADDR      RESW  1
MAIN      START 100
          LDX   FP
          JSUB  _main

_println  J     __println

_main     CLEAR S
          LDA #3
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          RMO   A,S
          LDA #1
          STS ADDR
          STA @ADDR
          CLEAR S
          LDA #6
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          RMO   A,S
          LDA #1
          STS ADDR
          STA @ADDR
          CLEAR S
          LDA #9
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          RMO   A,S
          LDA #0
          STS ADDR
          STA @ADDR
L2        CLEAR S
          LDA #6
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          STA ADDR
          LDS @ADDR
          LDA #4000
          COMPR S,A
          JLT   L3
L5        J     L4
L3        CLEAR S
          LDA #12
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          RMO   A,S
          CLEAR T
          LDA #3
          SUBR  A,T
          RMO   X,A
          ADDR  T,A
          STA ADDR
          LDA @ADDR
          CLEAR B
          LDT #6
          SUBR  T,B
          RMO   X,T
          ADDR  B,T
          STT ADDR
          LDT @ADDR
          RMO   A,A
          ADDR  T,A
          STS ADDR
          STA @ADDR
          CLEAR S
          LDA #3
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          RMO   A,T
          CLEAR S
          LDA #6
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          STA ADDR
          LDA @ADDR
          STT ADDR
          STA @ADDR
          CLEAR S
          LDA #6
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          RMO   A,T
          CLEAR S
          LDA #12
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          STA ADDR
          LDA @ADDR
          STT ADDR
          STA @ADDR
          CLEAR S
          LDA #12
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          STA ADDR
          LDA @ADDR
          RMO   A,T
          LDA #2
          RMO   A,S
          RMO   T,A
          DIVR  S,A
          RMO   A,A
          MULR  S,A
          RMO   T,S
          SUBR  A,S
          LDA #0
          COMPR S,A
          JEQ   L0
L6        J     L1
L0        CLEAR S
          LDA #9
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          RMO   A,S
          CLEAR T
          LDA #9
          SUBR  A,T
          RMO   X,A
          ADDR  T,A
          STA ADDR
          LDA @ADDR
          CLEAR B
          LDT #12
          SUBR  T,B
          RMO   X,T
          ADDR  B,T
          STT ADDR
          LDT @ADDR
          RMO   A,A
          ADDR  T,A
          STS ADDR
          STA @ADDR
L1        J     L2
L4        CLEAR S
          LDA #9
          SUBR  A,S
          RMO   X,A
          ADDR  S,A
          STA ADDR
          LDA @ADDR
          RMO   A,S
          +LDA 250
          LDA #3
          ADDR  A,A
          LDA #3
          SUBR  A,A
          STA ADDR
          STS @ADDR
          JSUB  _println
          RMO   A,A
          LDA #0
          RMO   A,A
          J     __main
